/*
 * generated by Xtext 2.10.0
 */
package nl.esi.comma.types


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class TypesStandaloneSetup extends TypesStandaloneSetupGenerated {

	def static void doSetup() {
		new TypesStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
