/**
 * generated by Xtext 2.36.0
 */
package nl.esi.comma.behavior.scl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class SclUiModule extends AbstractSclUiModule {
  public SclUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
