/*
 * generated by Xtext 2.36.0
 */
package nl.esi.comma.abstrracttestspecification.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class AbstractTestspecificationUiModule extends AbstractAbstractTestspecificationUiModule {
}
