/*
 * generated by Xtext 2.29.0
 */
package nl.asml.matala.product;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class ProductStandaloneSetup extends ProductStandaloneSetupGenerated {

	public static void doSetup() {
		new ProductStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
