/*
 * generated by Xtext 2.36.0
 */
package nl.esi.xtext.common.lang


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class BaseStandaloneSetup extends BaseStandaloneSetupGenerated {

	def static void doSetup() {
		new BaseStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
