/*
 * generated by Xtext 2.19.0
 */
package nl.esi.comma.systemconfig.ide

import nl.esi.comma.types.ide.contentassist.TypesIdeContentProposalCreator
import org.eclipse.xtext.ide.editor.contentassist.IdeContentProposalCreator

/**
 * Use this class to register ide components.
 */
class ConfigurationIdeModule extends AbstractConfigurationIdeModule {
    def Class<? extends IdeContentProposalCreator> bindIdeContentProposalCreator() {
        return TypesIdeContentProposalCreator
    }
}
