////
  // Copyright (c) 2024, 2025 TNO-ESI
  //
  // See the NOTICE file(s) distributed with this work for additional
  // information regarding copyright ownership.
  //
  // This program and the accompanying materials are made available
  // under the terms of the MIT License which is available at
  // https://opensource.org/licenses/MIT
  //
  // SPDX-License-Identifier: MIT
////

[[add-or-change-documentation-in-bundle]]
=== Add or change documentation in a bundle

. Add an `adoc/` folder to the root of your bundle (if not already present).
+
.Source tree (minimal)
----
    my.bundle/
      src/
      adoc/
        nl.my.bundle.adoc
        images/
----

. Ensure the folder is exported in the bundle build (include it in `build.properties`). This way the adoc can be included when the bundle is used as a binary dependency.
+
----
    bin.includes = META-INF/,\
                   .,\
                   adoc/
----

. Add developer documentation files (`*.adoc`) in this `adoc/` folder.

. Add your plugin as a dependency in the nl.asml.matala.design bundle.

. Add a reference to a 'main' index file for example `_section_xtext_languages.adoc`.
+
----
    include::{extdocdir}/nl.esi.comma.types.adoc[leveloffset=2]
----
+
[NOTE]
====
A maven build ensures that the required adoc files are copied from their binary dependencies.
Please run:
----
    mvn package -am -pl :nl.asml.matala.doc.design
----
====

