/**
 * Copyright (c) 2024, 2026 TNO-ESI
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 */
/*
 * generated by Xtext 2.10.0
 */
package nl.esi.xtext.expressions.scoping

import nl.esi.xtext.expressions.expression.ExpressionBinary
import nl.esi.xtext.expressions.expression.ExpressionEnumLiteral
import nl.esi.xtext.expressions.expression.ExpressionFunctionCall
import nl.esi.xtext.expressions.expression.ExpressionPackage
import nl.esi.xtext.expressions.expression.ExpressionRecord
import nl.esi.xtext.expressions.expression.ExpressionRecordAccess
import nl.esi.xtext.expressions.expression.ExpressionVector
import nl.esi.xtext.expressions.expression.Field
import nl.esi.xtext.expressions.expression.FunctionDecl
import nl.esi.xtext.types.types.EnumTypeDecl
import nl.esi.xtext.types.types.RecordTypeDecl
import nl.esi.xtext.types.types.TypeObject
import nl.esi.xtext.types.types.TypesPackage
import org.eclipse.emf.ecore.EObject
import org.eclipse.emf.ecore.EReference
import org.eclipse.emf.ecore.EStructuralFeature
import org.eclipse.xtext.scoping.IScope
import org.eclipse.xtext.scoping.Scopes

import static org.eclipse.xtext.scoping.Scopes.*

import static extension nl.esi.xtext.expressions.utilities.ExpressionsUtilities.*
import static extension nl.esi.xtext.types.utilities.TypeUtilities.*
import static extension org.eclipse.xtext.EcoreUtil2.*

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
class ExpressionScopeProvider extends AbstractExpressionScopeProvider {
    
    override getScope(EObject context, EReference reference) {
 
        val contextType = context.getContextType(reference)
       
        switch (context) {
            case contextType instanceof EnumTypeDecl  && reference == ExpressionPackage.Literals.EXPRESSION_ENUM_LITERAL__LITERAL: {
                return scopeFor((contextType as EnumTypeDecl).literals)
            }
            ExpressionRecord case reference == ExpressionPackage.Literals.FIELD__RECORD_FIELD: {
                return scopeFor(context.type.allFields)
            }
            ExpressionRecordAccess case reference == ExpressionPackage.Literals.EXPRESSION_RECORD_ACCESS__FIELD: {
                val type = context.record.typeOf
                return type instanceof RecordTypeDecl ? scopeFor(type.allFields) : IScope.NULLSCOPE
            }
            Field case reference == ExpressionPackage.Literals.FIELD__RECORD_FIELD: {
                val rec = context.eContainer
                return rec instanceof ExpressionRecord ? scopeFor(rec.type.allFields) : IScope.NULLSCOPE
            }
            ExpressionFunctionCall case reference == ExpressionPackage.Literals.EXPRESSION_FUNCTION_CALL__FUNCTION: {
                // Use custom scope that implements three-phase matching:
                // 1. Exact type match (arg count + types)
                // 2. Size match (arg count only - for better error messages)
                // 3. First function (any overload - for error reporting)
                return new FunctionOverloadScope(delegateGetScope(context, reference), context)
            }
            case reference == TypesPackage.Literals.TYPE__TYPE: {
                val funcDecl = context.getContainerOfType(FunctionDecl)
                val parent = delegateGetScope(context, reference)
                if (funcDecl !==null && !funcDecl.typeParams.empty) {
                    return Scopes.scopeFor(funcDecl.typeParams, parent)
                }
                return parent
            }
        }

        return super.getScope(context, reference)
    }

    override getContextType(EObject context, EStructuralFeature reference) {
        var TypeObject type = switch (context) {
            Field case reference != ExpressionPackage.Literals.FIELD__RECORD_FIELD: {
                context.recordField?.type?.type
            }
            ExpressionEnumLiteral case reference == ExpressionPackage.Literals.EXPRESSION_ENUM_LITERAL__LITERAL: {
                context.type
            }
            ExpressionBinary case reference != ExpressionPackage.Literals.EXPRESSION_BINARY__LEFT: {
                typeOf(context.left)
            }
            ExpressionVector: {
                val vct = typeOf(context)
                vct === null ? null : vct.elementType
            }
        }
        return type
    }

    protected def scope_forEnum(TypeObject type, EReference ref) {
        return if (type instanceof EnumTypeDecl && ref == ExpressionPackage.Literals.EXPRESSION_ENUM_LITERAL__LITERAL) {
            Scopes.scopeFor((type as EnumTypeDecl).literals)
        } else  {
            IScope.NULLSCOPE
        }
    }

}
