////
  // Copyright (c) 2024, 2026 TNO-ESI
  //
  // This program and the accompanying materials are made
  // available under the terms of the Eclipse Public License 2.0
  // which is available at https://www.eclipse.org/legal/epl-2.0/
  //
  // SPDX-License-Identifier: EPL-2.0
////

include::../_initCommon.adoc[]

[[add-or-change-documentation-in-bundle]]
= Add or change documentation in a bundle

. Add an `adoc/` folder to the root of your bundle (if not already present).
+
.Source tree (minimal)
----
    my.bundle/
      src/
      adoc/
        nl.my.bundle.adoc
        images/
----

. Ensure the folder is exported in the bundle build (include it in `build.properties`). This way the adoc can be included when the bundle is used as a binary dependency.
+
----
    bin.includes = META-INF/,\
                   .,\
                   adoc/
----

. Add developer documentation files (`*.adoc`) in this `adoc/` folder.

. Add your plugin as a dependency in the nl.esi.xplus.design bundle.

. Add a reference to a 'main' index file for example `_section_xtext_languages.adoc`.
+
----
    include::{extdocdir}/nl.esi.xtext.types.adoc[leveloffset=2]
----
+
[NOTE]
====
A maven build ensures that the required adoc files are copied from their binary dependencies.
Please run:
----
    mvn package -am -pl :nl.esi.xplus.doc.design
----
====

