@startuml
optJob --> [PrintFactoryOptimization_ComposeOptimizationJob_default@null@COMPOSE@]
inspectionReport --> [PrintFactoryOptimization_ComposeOptimizationJob_default@null@COMPOSE@]
[PrintFactoryOptimization_ComposeOptimizationJob_default@null@COMPOSE@] --> optimizeJob
[PrintFactoryOptimization_ComposeOptimizationJob_default@null@COMPOSE@] --> Flow_0y8u5pd
[PrintFactoryOptimization_ComposeOptimizationJob_default@null@COMPOSE@] --> inspectionReport
optimizeJob --> [PrintFactoryOptimization_RunOptimizationJob_default@ExecuteOptimizer@RUN@]
Flow_0y8u5pd --> [PrintFactoryOptimization_RunOptimizationJob_default@ExecuteOptimizer@RUN@]
[PrintFactoryOptimization_RunOptimizationJob_default@ExecuteOptimizer@RUN@] --> Event_1oozdnw
[PrintFactoryOptimization_RunOptimizationJob_default@ExecuteOptimizer@RUN@] --> corrections
[PrintFactoryOptimization_RunOptimizationJob_default@ExecuteOptimizer@RUN@] --> optResult
request --> [PrintFactoryA3DPrinter_RunPrintJob_default@ExecutePrinter@RUN@]
Flow_1u2qmtt --> [PrintFactoryA3DPrinter_RunPrintJob_default@ExecutePrinter@RUN@]
[PrintFactoryA3DPrinter_RunPrintJob_default@ExecutePrinter@RUN@] --> printResult
[PrintFactoryA3DPrinter_RunPrintJob_default@ExecutePrinter@RUN@] --> printReport
[PrintFactoryA3DPrinter_RunPrintJob_default@ExecutePrinter@RUN@] --> Event_0jcg6zx
corrections --> [PrintFactoryA3DPrinter_ComposePrintJob_default@null@COMPOSE@]
printJob --> [PrintFactoryA3DPrinter_ComposePrintJob_default@null@COMPOSE@]
[PrintFactoryA3DPrinter_ComposePrintJob_default@null@COMPOSE@] --> request
[PrintFactoryA3DPrinter_ComposePrintJob_default@null@COMPOSE@] --> Flow_1u2qmtt
printJob --> [PrintFactoryA3DPrinter_ComposePrepareJob_default@null@COMPOSE@]
[PrintFactoryA3DPrinter_ComposePrepareJob_default@null@COMPOSE@] --> request
[PrintFactoryA3DPrinter_ComposePrepareJob_default@null@COMPOSE@] --> Flow_0iaelzn
request --> [PrintFactoryA3DPrinter_RunPrepareJob_default@ExecutePrinter@RUN@]
Flow_0iaelzn --> [PrintFactoryA3DPrinter_RunPrepareJob_default@ExecutePrinter@RUN@]
[PrintFactoryA3DPrinter_RunPrepareJob_default@ExecutePrinter@RUN@] --> printResult
[PrintFactoryA3DPrinter_RunPrepareJob_default@ExecutePrinter@RUN@] --> Event_0mxx05p
measureRequest --> [PrintFactoryInspection_RunVisualinspection_default@ExecuteInspection@RUN@]
Flow_07l0yyj --> [PrintFactoryInspection_RunVisualinspection_default@ExecuteInspection@RUN@]
[PrintFactoryInspection_RunVisualinspection_default@ExecuteInspection@RUN@] --> inspectionResult
[PrintFactoryInspection_RunVisualinspection_default@ExecuteInspection@RUN@] --> inspectionReport
printReport --> [PrintFactoryInspection_ComposeVisualInspectionJob_default@null@COMPOSE@]
inspectionJob --> [PrintFactoryInspection_ComposeVisualInspectionJob_default@null@COMPOSE@]
[PrintFactoryInspection_ComposeVisualInspectionJob_default@null@COMPOSE@] --> measureRequest
[PrintFactoryInspection_ComposeVisualInspectionJob_default@null@COMPOSE@] --> printReport
[PrintFactoryInspection_ComposeVisualInspectionJob_default@null@COMPOSE@] --> Flow_07l0yyj
printRequests --> [PrintFactoryFactoryAutomation_SendPrintJob_default@null@INTERNAL@]
Gateway_1wpvmtk --> [PrintFactoryFactoryAutomation_SendPrintJob_default@null@INTERNAL@]
[PrintFactoryFactoryAutomation_SendPrintJob_default@null@INTERNAL@] --> printJob
[PrintFactoryFactoryAutomation_SendPrintJob_default@null@INTERNAL@] --> Flow_16s4ey1
Gateway_0p2uo9v --> [PrintFactoryFactoryAutomation_NextJob_default@null@INTERNAL@]
[PrintFactoryFactoryAutomation_NextJob_default@null@INTERNAL@] --> Gateway_1wpvmtk
Flow_01m2s0h --> [PrintFactoryFactoryAutomation_WaitforOptimizationJob_default@null@INTERNAL@]
optResult --> [PrintFactoryFactoryAutomation_WaitforOptimizationJob_default@null@INTERNAL@]
[PrintFactoryFactoryAutomation_WaitforOptimizationJob_default@null@INTERNAL@] --> Flow_09b0flo
Flow_09b0flo --> [PrintFactoryFactoryAutomation_Gateway_1f8wap6_default@null@INTERNAL@]
Flow_1vq9t2p --> [PrintFactoryFactoryAutomation_Gateway_1f8wap6_default@null@INTERNAL@]
[PrintFactoryFactoryAutomation_Gateway_1f8wap6_default@null@INTERNAL@] --> Gateway_0p2uo9v
Flow_1dcdx0e --> [PrintFactoryFactoryAutomation_Gateway_1j3rupx_default@null@INTERNAL@]
[PrintFactoryFactoryAutomation_Gateway_1j3rupx_default@null@INTERNAL@] --> Flow_1f74bn4
[PrintFactoryFactoryAutomation_Gateway_1j3rupx_default@null@INTERNAL@] --> Flow_1y4bjf4
inspectionResult --> [PrintFactoryFactoryAutomation_WaitforVisualInspection_default@null@INTERNAL@]
Flow_1dt29vl --> [PrintFactoryFactoryAutomation_WaitforVisualInspection_default@null@INTERNAL@]
[PrintFactoryFactoryAutomation_WaitforVisualInspection_default@null@INTERNAL@] --> Flow_0kbycuh
Flow_0fe8hce --> [PrintFactoryFactoryAutomation_SendOptimizationJob_default@null@INTERNAL@]
[PrintFactoryFactoryAutomation_SendOptimizationJob_default@null@INTERNAL@] --> optJob
[PrintFactoryFactoryAutomation_SendOptimizationJob_default@null@INTERNAL@] --> Flow_01m2s0h
Flow_1f74bn4 --> [PrintFactoryFactoryAutomation_PreparePrinter_default@null@INTERNAL@]
[PrintFactoryFactoryAutomation_PreparePrinter_default@null@INTERNAL@] --> printJob
[PrintFactoryFactoryAutomation_PreparePrinter_default@null@INTERNAL@] --> Flow_1rkhqnd
Flow_0kbycuh --> [PrintFactoryFactoryAutomation_AssertVisualInspection_default@Assert_Visual_Inspection@ASSERT@]
inspectionReport --> [PrintFactoryFactoryAutomation_AssertVisualInspection_default@Assert_Visual_Inspection@ASSERT@]
[PrintFactoryFactoryAutomation_AssertVisualInspection_default@Assert_Visual_Inspection@ASSERT@] --> Flow_0fe8hce
[PrintFactoryFactoryAutomation_AssertVisualInspection_default@Assert_Visual_Inspection@ASSERT@] --> inspectionReport
Flow_1y4bjf4 --> [PrintFactoryFactoryAutomation_SendVisualInspectionJob_default@null@INTERNAL@]
[PrintFactoryFactoryAutomation_SendVisualInspectionJob_default@null@INTERNAL@] --> inspectionJob
[PrintFactoryFactoryAutomation_SendVisualInspectionJob_default@null@INTERNAL@] --> Flow_1dt29vl
printResult --> [PrintFactoryFactoryAutomation_WaitforPrepare_default@null@INTERNAL@]
Flow_1rkhqnd --> [PrintFactoryFactoryAutomation_WaitforPrepare_default@null@INTERNAL@]
[PrintFactoryFactoryAutomation_WaitforPrepare_default@null@INTERNAL@] --> Flow_1vq9t2p
printResult --> [PrintFactoryFactoryAutomation_WaitforPrintJob_default@null@INTERNAL@]
Flow_16s4ey1 --> [PrintFactoryFactoryAutomation_WaitforPrintJob_default@null@INTERNAL@]
[PrintFactoryFactoryAutomation_WaitforPrintJob_default@null@INTERNAL@] --> Flow_1dcdx0e
@enduml
