/*
 * generated by Xtext 2.36.0
 */
package nl.esi.comma.xpath.scoping;


/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
public class XpathScopeProvider extends AbstractXpathScopeProvider {

}
