/**
 * Copyright (c) 2024, 2025 TNO-ESI
 *
 * See the NOTICE file(s) distributed with this work for additional
 * information regarding copyright ownership.
 *
 * This program and the accompanying materials are made available
 * under the terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT
 *
 * SPDX-License-Identifier: MIT
 */
/*
 * generated by Xtext 2.12.0
 */
package nl.esi.comma.scenarios.validation

import nl.esi.comma.scenarios.scenarios.Scenarios
import nl.esi.xtext.common.lang.base.BasePackage
import org.eclipse.emf.ecore.EClass
import org.eclipse.xtext.validation.Check

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class ScenariosValidator extends AbstractScenariosValidator {
	
    override protected isValidImportType(EClass importType) {
        return BasePackage.Literals.MODEL_CONTAINER.isSuperTypeOf(importType)
    }
	
	@Check
	def checkDuplicatedNamesInScenarios(Scenarios s){
		checkForNameDuplications(s.scenarios, "scenario", null)
	}

}
