/*
 * generated by Xtext 2.25.0
 */
package nl.esi.comma.behavior.scl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class SclUiModule extends AbstractSclUiModule {

	public SclUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
