/**
 * Copyright (c) 2024, 2025 TNO-ESI
 *
 * See the NOTICE file(s) distributed with this work for additional
 * information regarding copyright ownership.
 *
 * This program and the accompanying materials are made available
 * under the terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT
 *
 * SPDX-License-Identifier: MIT
 */
/*
 * generated by Xtext 2.36.0
 */
package nl.esi.comma.testspecification.validation

import nl.esi.comma.actions.actions.ActionsPackage
import nl.esi.comma.actions.actions.AssignmentAction
import nl.esi.comma.actions.actions.RecordFieldAssignmentAction
import nl.esi.comma.inputspecification.inputSpecification.InputSpecificationPackage
import nl.esi.comma.testspecification.testspecification.RefStep
import org.eclipse.emf.ecore.EClass
import org.eclipse.xtext.validation.Check

import static extension nl.esi.xtext.common.lang.utilities.EcoreUtil3.serialize

/**
 * This class contains custom validation rules. 
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class TestspecificationValidator extends AbstractTestspecificationValidator {

    override protected isValidImportType(EClass importType) {
        return InputSpecificationPackage.Literals.MAIN.isSuperTypeOf(importType)
    }

    @Check
    def protected void checkDataOverwrite(RefStep refStep) {
        val assignments = newHashSet
        for (action : refStep.input.actions.reverseView) {
            switch action {
                AssignmentAction: {
                    if (!assignments.add(action.assignment.serialize)) {
                        warning('Value is ignored as it is overwritten later', action,
                            ActionsPackage.Literals.ASSIGNMENT_ACTION__ASSIGNMENT)
                    }
                }
                RecordFieldAssignmentAction: {
                    if (!assignments.add(action.fieldAccess.serialize)) {
                        warning('Value is ignored as it is overwritten later', action,
                            ActionsPackage.Literals.RECORD_FIELD_ASSIGNMENT_ACTION__FIELD_ACCESS)
                    }
                }
            }
        }
    }
}
