/*
 * generated by Xtext 2.29.0
 */
package nl.asml.matala.product.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class ProductUiModule extends AbstractProductUiModule {

	public ProductUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
