/*
 * generated by Xtext 2.36.0
 */
package nl.esi.comma.behavior.scl.ide

import com.google.inject.Guice
import nl.esi.comma.behavior.scl.SclRuntimeModule
import nl.esi.comma.behavior.scl.SclStandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class SclIdeSetup extends SclStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new SclRuntimeModule, new SclIdeModule))
	}
	
}
