/*
 * generated by Xtext 2.25.0
 */
package nl.esi.comma.behavior.scl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import nl.esi.comma.behavior.scl.SclRuntimeModule;
import nl.esi.comma.behavior.scl.SclStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class SclIdeSetup extends SclStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new SclRuntimeModule(), new SclIdeModule()));
	}
	
}
