/*
 * generated by Xtext 2.36.0
 */
package nl.esi.comma.causalgraph


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class CausalGraphRuntimeModule extends AbstractCausalGraphRuntimeModule {
}
