@startuml
EqStatus --> [SupervisonModelSupervisionPressureHandler_StartPump_default@null@COMPOSE@]
VacuumRequest --> [SupervisonModelSupervisionPressureHandler_StartPump_default@null@COMPOSE@]
Gateway_1j81da5 --> [SupervisonModelSupervisionPressureHandler_StartPump_default@null@COMPOSE@]
[SupervisonModelSupervisionPressureHandler_StartPump_default@null@COMPOSE@] --> PumpRequest
[SupervisonModelSupervisionPressureHandler_StartPump_default@null@COMPOSE@] --> Flow_0balrow
[SupervisonModelSupervisionPressureHandler_StartPump_default@null@COMPOSE@] --> EqStatus
PumpUpdate --> [SupervisonModelSupervisionPressureHandler_WaitforPumpOff_default@null@INTERNAL@]
EqStatus --> [SupervisonModelSupervisionPressureHandler_WaitforPumpOff_default@null@INTERNAL@]
Flow_0cjhiik --> [SupervisonModelSupervisionPressureHandler_WaitforPumpOff_default@null@INTERNAL@]
[SupervisonModelSupervisionPressureHandler_WaitforPumpOff_default@null@INTERNAL@] --> VacuumUpdate
[SupervisonModelSupervisionPressureHandler_WaitforPumpOff_default@null@INTERNAL@] --> Gateway_1i0qy9g
[SupervisonModelSupervisionPressureHandler_WaitforPumpOff_default@null@INTERNAL@] --> EqStatus
Gateway_1i0qy9g --> [SupervisonModelSupervisionPressureHandler_Restart_default@null@INTERNAL@]
[SupervisonModelSupervisionPressureHandler_Restart_default@null@INTERNAL@] --> Gateway_1j81da5
Flow_1wguswc --> [SupervisonModelSupervisionPressureHandler_TurnOffPump_default@null@COMPOSE@]
EqStatus --> [SupervisonModelSupervisionPressureHandler_TurnOffPump_default@null@COMPOSE@]
VacuumRequest --> [SupervisonModelSupervisionPressureHandler_TurnOffPump_default@null@COMPOSE@]
[SupervisonModelSupervisionPressureHandler_TurnOffPump_default@null@COMPOSE@] --> PumpRequest
[SupervisonModelSupervisionPressureHandler_TurnOffPump_default@null@COMPOSE@] --> EqStatus
[SupervisonModelSupervisionPressureHandler_TurnOffPump_default@null@COMPOSE@] --> Flow_0cjhiik
PumpUpdate --> [SupervisonModelSupervisionPressureHandler_WaitforPumpStated_default@null@INTERNAL@]
Flow_0balrow --> [SupervisonModelSupervisionPressureHandler_WaitforPumpStated_default@null@INTERNAL@]
EqStatus --> [SupervisonModelSupervisionPressureHandler_WaitforPumpStated_default@null@INTERNAL@]
[SupervisonModelSupervisionPressureHandler_WaitforPumpStated_default@null@INTERNAL@] --> Flow_1wguswc
[SupervisonModelSupervisionPressureHandler_WaitforPumpStated_default@null@INTERNAL@] --> VacuumUpdate
[SupervisonModelSupervisionPressureHandler_WaitforPumpStated_default@null@INTERNAL@] --> EqStatus
Flow_1w9tlf4 --> [SupervisonModelAcquisitionController_AcquisitionStopped_default@null@INTERNAL@]
[SupervisonModelAcquisitionController_AcquisitionStopped_default@null@INTERNAL@] --> AcqUpdate
[SupervisonModelAcquisitionController_AcquisitionStopped_default@null@INTERNAL@] --> Gateway_0h81kts
AcquisitionReq --> [SupervisonModelAcquisitionController_Execacquisitioninitandteardown_default@ExecAcquisitionCommand@RUN@]
[SupervisonModelAcquisitionController_Execacquisitioninitandteardown_default@ExecAcquisitionCommand@RUN@] --> Flow_084nmm6
AcquisitionReq --> [SupervisonModelAcquisitionController_StartAcquisition_default@ExecAcquisitionCommand@RUN@]
[SupervisonModelAcquisitionController_StartAcquisition_default@ExecAcquisitionCommand@RUN@] --> Flow_1rusz82
Flow_084nmm6 --> [SupervisonModelAcquisitionController_Acquisitionexecdone_default@null@INTERNAL@]
[SupervisonModelAcquisitionController_Acquisitionexecdone_default@null@INTERNAL@] --> AcqUpdate
[SupervisonModelAcquisitionController_Acquisitionexecdone_default@null@INTERNAL@] --> Gateway_0h81kts
AcquisitionReq --> [SupervisonModelAcquisitionController_StopAcquisition_default@ExecAcquisitionCommand@RUN@]
[SupervisonModelAcquisitionController_StopAcquisition_default@ExecAcquisitionCommand@RUN@] --> ImageData
[SupervisonModelAcquisitionController_StopAcquisition_default@ExecAcquisitionCommand@RUN@] --> Flow_1w9tlf4
Flow_1rusz82 --> [SupervisonModelAcquisitionController_AcquisitionStarted_default@null@INTERNAL@]
[SupervisonModelAcquisitionController_AcquisitionStarted_default@null@INTERNAL@] --> AcqUpdate
[SupervisonModelAcquisitionController_AcquisitionStarted_default@null@INTERNAL@] --> Gateway_0h81kts
Gateway_12yhscn --> [SupervisonModelTemperatureController_return_default@null@INTERNAL@]
[SupervisonModelTemperatureController_return_default@null@INTERNAL@] --> Gateway_1sv33t8
Gateway_1sv33t8 --> [SupervisonModelTemperatureController_CheckTemp_default@TempCheck@ASSERT@]
temp_achieved --> [SupervisonModelTemperatureController_CheckTemp_default@TempCheck@ASSERT@]
[SupervisonModelTemperatureController_CheckTemp_default@TempCheck@ASSERT@] --> Flow_01g3o4k
Event_1r2zvr6 --> [SupervisonModelTemperatureController_SetTemperature_default@null@INTERNAL@]
[SupervisonModelTemperatureController_SetTemperature_default@null@INTERNAL@] --> Flow_0estwso
[SupervisonModelTemperatureController_SetTemperature_default@null@INTERNAL@] --> TempRequest
Flow_01g3o4k --> [SupervisonModelTemperatureController_ResetTemperature_default@null@INTERNAL@]
[SupervisonModelTemperatureController_ResetTemperature_default@null@INTERNAL@] --> Flow_0ay6jpo
[SupervisonModelTemperatureController_ResetTemperature_default@null@INTERNAL@] --> TempRequest
Flow_0ay6jpo --> [SupervisonModelTemperatureController_WaitforReset_default@null@INTERNAL@]
TempUpdate --> [SupervisonModelTemperatureController_WaitforReset_default@null@INTERNAL@]
[SupervisonModelTemperatureController_WaitforReset_default@null@INTERNAL@] --> Gateway_12yhscn
TempUpdate --> [SupervisonModelTemperatureController_WaitforTempSet_default@null@INTERNAL@]
Flow_0estwso --> [SupervisonModelTemperatureController_WaitforTempSet_default@null@INTERNAL@]
[SupervisonModelTemperatureController_WaitforTempSet_default@null@INTERNAL@] --> Gateway_1sv33t8
TempRequest --> [SupervisonModelSupervisionTemperatureHandler_CreateResetTempMessage_default@null@COMPOSE@]
EqStatus --> [SupervisonModelSupervisionTemperatureHandler_CreateResetTempMessage_default@null@COMPOSE@]
[SupervisonModelSupervisionTemperatureHandler_CreateResetTempMessage_default@null@COMPOSE@] --> Gateway_1qk9wqe
[SupervisonModelSupervisionTemperatureHandler_CreateResetTempMessage_default@null@COMPOSE@] --> EqStatus
[SupervisonModelSupervisionTemperatureHandler_CreateResetTempMessage_default@null@COMPOSE@] --> TempCMD
Gateway_1qk9wqe --> [SupervisonModelSupervisionTemperatureHandler_ExecuteSetTemp_default@SetTemperature@RUN@]
EqStatus --> [SupervisonModelSupervisionTemperatureHandler_ExecuteSetTemp_default@SetTemperature@RUN@]
TempCMD --> [SupervisonModelSupervisionTemperatureHandler_ExecuteSetTemp_default@SetTemperature@RUN@]
[SupervisonModelSupervisionTemperatureHandler_ExecuteSetTemp_default@SetTemperature@RUN@] --> TempUpdate
[SupervisonModelSupervisionTemperatureHandler_ExecuteSetTemp_default@SetTemperature@RUN@] --> Event_13ys7sy
[SupervisonModelSupervisionTemperatureHandler_ExecuteSetTemp_default@SetTemperature@RUN@] --> temp_achieved
[SupervisonModelSupervisionTemperatureHandler_ExecuteSetTemp_default@SetTemperature@RUN@] --> EqStatus
TempRequest --> [SupervisonModelSupervisionTemperatureHandler_CreateSetTempMessage_default@null@COMPOSE@]
[SupervisonModelSupervisionTemperatureHandler_CreateSetTempMessage_default@null@COMPOSE@] --> Gateway_1qk9wqe
[SupervisonModelSupervisionTemperatureHandler_CreateSetTempMessage_default@null@COMPOSE@] --> TempCMD
Flow_0x0gs9b --> [SupervisonModelPumpController_done_default@null@INTERNAL@]
[SupervisonModelPumpController_done_default@null@INTERNAL@] --> Gateway_0td58pc
[SupervisonModelPumpController_done_default@null@INTERNAL@] --> PumpUpdate
PumpRequest --> [SupervisonModelPumpController_startpump_default@ExecPumpCommand@RUN@]
[SupervisonModelPumpController_startpump_default@ExecPumpCommand@RUN@] --> Flow_0x0gs9b
PumpRequest --> [SupervisonModelPumpController_stoppump_default@ExecPumpCommand@RUN@]
[SupervisonModelPumpController_stoppump_default@ExecPumpCommand@RUN@] --> Flow_104f6k4
Flow_104f6k4 --> [SupervisonModelPumpController_pumpstopped_default@null@INTERNAL@]
[SupervisonModelPumpController_pumpstopped_default@null@INTERNAL@] --> Gateway_0td58pc
[SupervisonModelPumpController_pumpstopped_default@null@INTERNAL@] --> PumpUpdate
Flow_05szwsj --> [SupervisonModelImagingController_WaitforUnprepareImaging_default@null@INTERNAL@]
ImagingUpdate --> [SupervisonModelImagingController_WaitforUnprepareImaging_default@null@INTERNAL@]
[SupervisonModelImagingController_WaitforUnprepareImaging_default@null@INTERNAL@] --> Gateway_0gu94f4
Gateway_0gu94f4 --> [SupervisonModelImagingController_returntoprep_default@null@INTERNAL@]
[SupervisonModelImagingController_returntoprep_default@null@INTERNAL@] --> Gateway_0xpxevh
Gateway_0i3nw09 --> [SupervisonModelImagingController_UnprepareImaging_default@null@INTERNAL@]
[SupervisonModelImagingController_UnprepareImaging_default@null@INTERNAL@] --> ImagingRequest
[SupervisonModelImagingController_UnprepareImaging_default@null@INTERNAL@] --> Flow_05szwsj
Flow_0ncxpgd --> [SupervisonModelImagingController_WaitforImagingStopped_default@null@INTERNAL@]
ImagingUpdate --> [SupervisonModelImagingController_WaitforImagingStopped_default@null@INTERNAL@]
[SupervisonModelImagingController_WaitforImagingStopped_default@null@INTERNAL@] --> Gateway_0i3nw09
Gateway_0kvhy0o --> [SupervisonModelImagingController_StartLowResImaging_default@null@INTERNAL@]
[SupervisonModelImagingController_StartLowResImaging_default@null@INTERNAL@] --> ImagingRequest
[SupervisonModelImagingController_StartLowResImaging_default@null@INTERNAL@] --> Gateway_08l0os0
Gateway_0i3nw09 --> [SupervisonModelImagingController_nextimage_default@null@INTERNAL@]
[SupervisonModelImagingController_nextimage_default@null@INTERNAL@] --> Gateway_0kvhy0o
Gateway_0kvhy0o --> [SupervisonModelImagingController_StartHighResImaging_default@null@INTERNAL@]
[SupervisonModelImagingController_StartHighResImaging_default@null@INTERNAL@] --> ImagingRequest
[SupervisonModelImagingController_StartHighResImaging_default@null@INTERNAL@] --> Gateway_08l0os0
Flow_1k04xzh --> [SupervisonModelImagingController_Stopimaging_default@null@INTERNAL@]
[SupervisonModelImagingController_Stopimaging_default@null@INTERNAL@] --> ImagingRequest
[SupervisonModelImagingController_Stopimaging_default@null@INTERNAL@] --> Flow_0ncxpgd
Flow_029nrs5 --> [SupervisonModelImagingController_WaitforPrepared_default@null@INTERNAL@]
ImagingUpdate --> [SupervisonModelImagingController_WaitforPrepared_default@null@INTERNAL@]
[SupervisonModelImagingController_WaitforPrepared_default@null@INTERNAL@] --> Gateway_0kvhy0o
Gateway_0xpxevh --> [SupervisonModelImagingController_PrepareImaging_default@null@INTERNAL@]
[SupervisonModelImagingController_PrepareImaging_default@null@INTERNAL@] --> ImagingRequest
[SupervisonModelImagingController_PrepareImaging_default@null@INTERNAL@] --> Flow_029nrs5
Gateway_08l0os0 --> [SupervisonModelImagingController_ImagingFinished_default@null@INTERNAL@]
ImagingUpdate --> [SupervisonModelImagingController_ImagingFinished_default@null@INTERNAL@]
[SupervisonModelImagingController_ImagingFinished_default@null@INTERNAL@] --> Flow_1k04xzh
Flow_1erv6vq --> [SupervisonModelVacuumController_TurnOff_default@null@INTERNAL@]
[SupervisonModelVacuumController_TurnOff_default@null@INTERNAL@] --> Flow_1dvvja5
[SupervisonModelVacuumController_TurnOff_default@null@INTERNAL@] --> VacuumRequest
Gateway_0mqr7c2 --> [SupervisonModelVacuumController_SetVacuum_default@null@INTERNAL@]
[SupervisonModelVacuumController_SetVacuum_default@null@INTERNAL@] --> VacuumRequest
[SupervisonModelVacuumController_SetVacuum_default@null@INTERNAL@] --> Flow_1phqrfh
Gateway_07w0e8f --> [SupervisonModelVacuumController_return_default@null@INTERNAL@]
[SupervisonModelVacuumController_return_default@null@INTERNAL@] --> Gateway_0mqr7c2
VacuumUpdate --> [SupervisonModelVacuumController_WaitforOff_default@null@INTERNAL@]
Flow_1dvvja5 --> [SupervisonModelVacuumController_WaitforOff_default@null@INTERNAL@]
[SupervisonModelVacuumController_WaitforOff_default@null@INTERNAL@] --> Gateway_07w0e8f
VacuumUpdate --> [SupervisonModelVacuumController_WaitforVacuumSet_default@null@INTERNAL@]
Flow_1phqrfh --> [SupervisonModelVacuumController_WaitforVacuumSet_default@null@INTERNAL@]
[SupervisonModelVacuumController_WaitforVacuumSet_default@null@INTERNAL@] --> Flow_1erv6vq
AcqUpdate --> [SupervisonModelSupervisionImaging_WaitforStopAcquisition_default@null@INTERNAL@]
Flow_0678bm1 --> [SupervisonModelSupervisionImaging_WaitforStopAcquisition_default@null@INTERNAL@]
EqStatus --> [SupervisonModelSupervisionImaging_WaitforStopAcquisition_default@null@INTERNAL@]
[SupervisonModelSupervisionImaging_WaitforStopAcquisition_default@null@INTERNAL@] --> Gateway_16m9e4j
[SupervisonModelSupervisionImaging_WaitforStopAcquisition_default@null@INTERNAL@] --> EqStatus
[SupervisonModelSupervisionImaging_WaitforStopAcquisition_default@null@INTERNAL@] --> ImagingUpdate
ImageData --> [SupervisonModelSupervisionImaging_CheckLowResImageQuality_default@CheckAcquisitionResult@ASSERT@]
Gateway_16m9e4j --> [SupervisonModelSupervisionImaging_CheckLowResImageQuality_default@CheckAcquisitionResult@ASSERT@]
LastAcqReq --> [SupervisonModelSupervisionImaging_CheckLowResImageQuality_default@CheckAcquisitionResult@ASSERT@]
[SupervisonModelSupervisionImaging_CheckLowResImageQuality_default@CheckAcquisitionResult@ASSERT@] --> Gateway_0qg69ul
AcqUpdate --> [SupervisonModelSupervisionImaging_WaitforStartAcquisition_default@null@INTERNAL@]
EqStatus --> [SupervisonModelSupervisionImaging_WaitforStartAcquisition_default@null@INTERNAL@]
Flow_1bajtwc --> [SupervisonModelSupervisionImaging_WaitforStartAcquisition_default@null@INTERNAL@]
[SupervisonModelSupervisionImaging_WaitforStartAcquisition_default@null@INTERNAL@] --> Gateway_0qg69ul
[SupervisonModelSupervisionImaging_WaitforStartAcquisition_default@null@INTERNAL@] --> EqStatus
[SupervisonModelSupervisionImaging_WaitforStartAcquisition_default@null@INTERNAL@] --> ImagingUpdate
ImagingRequest --> [SupervisonModelSupervisionImaging_StopAcquisition_default@null@COMPOSE@]
[SupervisonModelSupervisionImaging_StopAcquisition_default@null@COMPOSE@] --> AcquisitionReq
[SupervisonModelSupervisionImaging_StopAcquisition_default@null@COMPOSE@] --> Flow_0678bm1
ImagingRequest --> [SupervisonModelSupervisionImaging_StartAcquisition_default@null@COMPOSE@]
EqStatus --> [SupervisonModelSupervisionImaging_StartAcquisition_default@null@COMPOSE@]
[SupervisonModelSupervisionImaging_StartAcquisition_default@null@COMPOSE@] --> AcquisitionReq
[SupervisonModelSupervisionImaging_StartAcquisition_default@null@COMPOSE@] --> LastAcqReq
[SupervisonModelSupervisionImaging_StartAcquisition_default@null@COMPOSE@] --> EqStatus
[SupervisonModelSupervisionImaging_StartAcquisition_default@null@COMPOSE@] --> Flow_1bajtwc
ImageData --> [SupervisonModelSupervisionImaging_CheckHighResImageQuality_default@CheckAcquisitionResult@ASSERT@]
Gateway_16m9e4j --> [SupervisonModelSupervisionImaging_CheckHighResImageQuality_default@CheckAcquisitionResult@ASSERT@]
LastAcqReq --> [SupervisonModelSupervisionImaging_CheckHighResImageQuality_default@CheckAcquisitionResult@ASSERT@]
[SupervisonModelSupervisionImaging_CheckHighResImageQuality_default@CheckAcquisitionResult@ASSERT@] --> Gateway_0qg69ul
ImagingRequest --> [SupervisonModelSupervisionImagePreparation_Unprepare_default@null@COMPOSE@]
[SupervisonModelSupervisionImagePreparation_Unprepare_default@null@COMPOSE@] --> AcquisitionReq
[SupervisonModelSupervisionImagePreparation_Unprepare_default@null@COMPOSE@] --> Flow_1kpcqqf
ImagingRequest --> [SupervisonModelSupervisionImagePreparation_Prepare_default@null@COMPOSE@]
EqStatus --> [SupervisonModelSupervisionImagePreparation_Prepare_default@null@COMPOSE@]
[SupervisonModelSupervisionImagePreparation_Prepare_default@null@COMPOSE@] --> Flow_0kkvgdv
[SupervisonModelSupervisionImagePreparation_Prepare_default@null@COMPOSE@] --> AcquisitionReq
[SupervisonModelSupervisionImagePreparation_Prepare_default@null@COMPOSE@] --> EqStatus
Flow_0kkvgdv --> [SupervisonModelSupervisionImagePreparation_Waitforprepare_default@null@INTERNAL@]
AcqUpdate --> [SupervisonModelSupervisionImagePreparation_Waitforprepare_default@null@INTERNAL@]
EqStatus --> [SupervisonModelSupervisionImagePreparation_Waitforprepare_default@null@INTERNAL@]
[SupervisonModelSupervisionImagePreparation_Waitforprepare_default@null@INTERNAL@] --> Gateway_102q82v
[SupervisonModelSupervisionImagePreparation_Waitforprepare_default@null@INTERNAL@] --> EqStatus
[SupervisonModelSupervisionImagePreparation_Waitforprepare_default@null@INTERNAL@] --> ImagingUpdate
AcqUpdate --> [SupervisonModelSupervisionImagePreparation_WaitforUnprepare_default@null@INTERNAL@]
EqStatus --> [SupervisonModelSupervisionImagePreparation_WaitforUnprepare_default@null@INTERNAL@]
Flow_1kpcqqf --> [SupervisonModelSupervisionImagePreparation_WaitforUnprepare_default@null@INTERNAL@]
[SupervisonModelSupervisionImagePreparation_WaitforUnprepare_default@null@INTERNAL@] --> Gateway_102q82v
[SupervisonModelSupervisionImagePreparation_WaitforUnprepare_default@null@INTERNAL@] --> EqStatus
[SupervisonModelSupervisionImagePreparation_WaitforUnprepare_default@null@INTERNAL@] --> ImagingUpdate
@enduml
