/*
 * generated by Xtext 2.36.0
 */
package nl.esi.comma.assertthat.ui.outline

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider

/**
 * Customization of the default outline structure.
 *
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#outline
 */
class AssertThatOutlineTreeProvider extends DefaultOutlineTreeProvider {

}
