/**
 * Copyright (c) 2024, 2025 TNO-ESI
 *
 * See the NOTICE file(s) distributed with this work for additional
 * information regarding copyright ownership.
 *
 * This program and the accompanying materials are made available
 * under the terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT
 *
 * SPDX-License-Identifier: MIT
 */
/*
 * generated by Xtext 2.12.0
 */
package nl.esi.comma.project.standard.ui

import nl.esi.xtext.common.lang.reporting.IStatusReporting
import nl.esi.xtext.common.lang.reporting.StatusReportingEclipseRuntime
import nl.esi.xtext.types.ui.contentassist.XPlusHyperLinkDetector
import org.eclipse.core.runtime.Platform
import org.eclipse.jface.text.hyperlink.IHyperlinkDetector
import com.google.inject.Provides
import org.eclipse.core.runtime.Plugin
import nl.esi.comma.project.standard.ui.internal.StandardActivator

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */

class StandardProjectUiModule extends AbstractStandardProjectUiModule {	

    final StandardActivator plugin 
    
	new(StandardActivator plugin) {
		super(plugin)
		this.plugin = plugin
		Platform.getBundle("org.eclipse.debug.ui").start
	}
	
	override Class<? extends IHyperlinkDetector> bindIHyperlinkDetector() {
		 return XPlusHyperLinkDetector
	}
	
	@Provides
    def Plugin providePlugin() {
        return this.plugin;
    }
	
    def Class<? extends IStatusReporting> bindIStatusReporter() {
        return StatusReportingEclipseRuntime
    }
	
	
}
