/*
 * generated by Xtext 2.36.0
 */
package nl.esi.comma.behavior.scl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class SclStandaloneSetup extends SclStandaloneSetupGenerated {

	def static void doSetup() {
		new SclStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
