/*
 * generated by Xtext 2.29.0
 */
package nl.esi.comma.testspecification.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class TestspecificationUiModule extends AbstractTestspecificationUiModule {

	public TestspecificationUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
