/*
 * Copyright (c) 2024, 2025 TNO-ESI
 *
 * See the NOTICE file(s) distributed with this work for additional
 * information regarding copyright ownership.
 *
 * This program and the accompanying materials are made available
 * under the terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT
 *
 * SPDX-License-Identifier: MIT
 */
/*
 * generated by Xtext 2.29.0
 */
package nl.esi.comma.testspecification.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ide.editor.contentassist.IdeContentProposalCreator;

import nl.esi.comma.types.ide.contentassist.TypesIdeContentProposalCreator;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class TestspecificationUiModule extends AbstractTestspecificationUiModule {

	public TestspecificationUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}

	public  Class<? extends IdeContentProposalCreator> bindIdeContentProposalCreator() {
        return TypesIdeContentProposalCreator.class;
    }
}
