/*
 * generated by Xtext 2.29.0
 */
package nl.esi.comma.testspecification.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import nl.esi.comma.testspecification.TestspecificationRuntimeModule;
import nl.esi.comma.testspecification.TestspecificationStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class TestspecificationIdeSetup extends TestspecificationStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new TestspecificationRuntimeModule(), new TestspecificationIdeModule()));
	}
	
}
