/**
 * Copyright (c) 2024, 2026 TNO-ESI
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 */
/*
 * generated by Xtext 2.36.0
 */
package nl.esi.xtext.expressions.tests

import com.google.inject.Inject
import nl.esi.xtext.expressions.expression.ExpressionModel
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith
import nl.esi.xtext.common.lang.utilities.EcoreUtil3

@ExtendWith(InjectionExtension)
@InjectWith(ExpressionInjectorProvider)
class ExpressionValidationTest {
    @Inject
    ParseHelper<ExpressionModel> parseHelper

    @Test
    def void testWildcardExpressionComparison() {
        validate('''
            int someValue = 3
            bool test = (someValue == *)
        ''')
    }

    @Test
    def void testLiterals() {
        validate('''
            bool b1 = true
            bool b2 = false
            int i = 42
            int j = -7
            real r1 = 3.14
            real r2 = 2.0e-5
            string s1 = "hello"
            string s2 = "John Smith"
            enum MyEnum{ A B }
            MyEnum ^e = MyEnum::A
            int[] v = <int[]>[1, 2, 3]
            record MyRecord { int field1, string field2 }
            MyRecord rec = MyRecord{field1 = 1, field2 = "x"}
            map<int, string> m = <map<int, string>>{1 -> "a", 2 -> "b"}
            bool n = null
        ''')
    }

    @Test
    def void testVariableInitialization() {
        validate('''
            int i
            string s = "hello"
            real x
            bool flag = true
        ''')
    }

    @Test
    def void testLogicalOperators() {
        validate('''
            bool a = true and false
            bool b = true or false
            bool c = not false
            bool d = true AND false OR NOT false
        ''')
    }

    @Test
    def void testComparisonOperators() {
        validate('''
            bool a = 1 == 1
            bool b = 2 != 3
            bool c = 2 < 3
            bool d = 2 <= 3
            bool ^e = 3 > 2
            bool f = 3 >= 2
        ''')
    }


   @Test
    def void testComparisonNull() {
        validate('''
            string nString = null
            bool a = nString == null
            bool b = null == nString
            bool c = null == null
            int i = null
            bool d = i == null
            bool ^e = null == i
            bool f = true == null and true != null
        ''')
    }

   @Test
    def void testComparisonAny() {
        validate('''
            bool a = true == *
            bool d = 3 == *
        ''')
    }

    @Test
    def void testArithmeticOperators() {
        validate('''
            int a = 1 + 2
            int b = 3 - 1
            int c = 2 * 3
            int d = 6 / 2
            int ^e = 7 mod 3
            int f = 2 ^ 3
            int g = 1 max 2
            int h = 1 min 2
        ''')
    }

    @Test
    def void testPostfixOperators() {
        validate('''
            record MyRecord { int field1, string field2 }
            MyRecord rec = MyRecord{field1 = 1, field2 = "x"}
            int f = rec.field1
            map<int, string> m = <map<int, string>>{1 -> "a"}
            string v = m[1]
        ''')
    }

    @Test
    def void testFunctionCalls() {
        validate('''
            function int sum(int[] v)
            int[] v = <int[]>[1, 2, 3]
            int s1 = sum(v)
            int[] s2 = range(1, 10, 2)
        ''')
    }

    @Test
    def void testFunctionCallsWithTemplates() {
        validate('''
            function <T> T sum(T[] v)
            int[] v = <int[]>[1, 2, 3]
            int s1 = sum(v)
            int[] s2 = range(1, 10, 2)
        ''')
    }

    @Test
    def void testParentheses() {
        validate('''
            int a = (1 + 2) * 3
        ''')
    }

    @Test
    def void testTypeAnnotation() {
        validate('''
            int[] v = <int[]>[1, 2, 3]
            map<int, string> m = <map<int, string>>{1 -> "a", 2 -> "b"}
        ''')
    }

    @Test
    def void testVectorsAndRecords() {
        validate('''
            record Person { string name, int age }
            int[] numbers = <int[]>[1, 2, 3]
            Person p = Person{name = "Alice", age = 30}
            int n = get(numbers, 0)
            string name = p.name
        ''')
    }

    @Test
    def void testMaps() {
        validate('''
            map<int, string> m = <map<int, string>>{1 -> "a", 2 -> "b"}
            string v = m[1]
            map<int, string>  v2 = m[2 -> "c"]
        ''')
    }

    @Test
    def void testNullValue() {
        validate('''
            string s = null
            int[] v = null
        ''')
    }

    @Test
    def void testOperatorPrecedence() {
        validate('''
            int a = 1 + 2 * 3
            int b = (1 + 2) * 3
            bool c = 1 < 2 and 2 < 3
            int d = 2 ^ 3 ^ 2
        ''')
    }

    private def validate(String text) {
        val result = parseHelper.parse(text)

        Assertions.assertNotNull(result)
        var errors = result.eResource.errors
        Assertions.assertTrue(errors.isEmpty, '''Unexpected parsing errors: «errors.join(", ")»''')
        EcoreUtil3.validate(result)
        errors = result.eResource.errors
        Assertions.assertTrue(errors.isEmpty, '''Unexpected validation errors: «errors.join(", ")»''')
        // test serialization
        EcoreUtil3.serialize(result)

    }
}