/*
 * generated by Xtext 2.36.0
 */
package nl.esi.comma.xpath.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import nl.esi.comma.xpath.XpathRuntimeModule;
import nl.esi.comma.xpath.XpathStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class XpathIdeSetup extends XpathStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new XpathRuntimeModule(), new XpathIdeModule()));
	}
	
}
