/*
 * generated by Xtext 2.19.0
 */
package nl.esi.comma.steps.ide

import com.google.inject.Guice
import nl.esi.comma.steps.StepRuntimeModule
import nl.esi.comma.steps.StepStandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class StepIdeSetup extends StepStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new StepRuntimeModule, new StepIdeModule))
	}
	
}
