/*
 * generated by Xtext 2.29.0
 */
package nl.esi.comma.testspecification.scoping;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EReference;
import org.eclipse.xtext.scoping.IScope;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
public class TestspecificationScopeProvider extends AbstractTestspecificationScopeProvider {

	@Override
	public IScope getScope(EObject ctx, EReference ref) {
		return super.getScope(ctx, ref);
	}
}
