/*
 * Copyright (c) 2024, 2025 TNO-ESI
 *
 * See the NOTICE file(s) distributed with this work for additional
 * information regarding copyright ownership.
 *
 * This program and the accompanying materials are made available
 * under the terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT
 *
 * SPDX-License-Identifier: MIT
 */
package nl.esi.comma.expressions.generator;

import java.lang.reflect.Method;
import java.lang.reflect.Modifier;
import java.lang.reflect.Parameter;
import java.lang.reflect.ParameterizedType;
import java.lang.reflect.Type;
import java.lang.reflect.TypeVariable;
import java.math.BigDecimal;
import java.util.Arrays;
import java.util.Collection;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.stream.Collectors;
import java.util.stream.IntStream;

import nl.esi.comma.expressions.expression.Expression;
import nl.esi.comma.expressions.expression.ExpressionMap;
import nl.esi.comma.expressions.expression.ExpressionVector;

/**
 * Reflects on a Java library class and generates {@code .expr} function
 * declarations. All {@code public} (static or instance) non-{@link Object}
 * methods are included; {@code void} returns are skipped.
 *
 * <p>Supports EMF expression types directly:
 * {@link ExpressionVector} → {@code any[]},
 * {@link ExpressionMap} → {@code map<any,any>},
 * {@link Expression} → {@code any}.
 */
public final class LibraryToExprGenerator {

	private LibraryToExprGenerator() {
	}

	/** Generates {@code .expr} content for all public static methods. */
	public static String generate(Class<?> libraryClass) {
		return buildContent(libraryClass);
	}

	/** Generates and writes {@code .expr} to the given path via the adapter. */
	public static void generate(Class<?> libraryClass, String outputPath, IFileSystemAccessAdapter fsa) {
		fsa.generateFile(outputPath, buildContent(libraryClass));
	}

	/** Generates and writes {@code .expr} using an auto-derived filename. */
	public static void generate(Class<?> libraryClass, IFileSystemAccessAdapter fsa) {
		generate(libraryClass, libraryClass.getSimpleName().toLowerCase() + ".expr", fsa);
	}

	/** Minimal file-writing abstraction to avoid a hard Xtext dependency. */
	@FunctionalInterface
	public interface IFileSystemAccessAdapter {
		void generateFile(String path, String content);
	}

	// -- Core generation ------------------------------------------------------

	private static String buildContent(Class<?> libraryClass) {
		Map<String, List<Method>> grouped = Arrays.stream(libraryClass.getDeclaredMethods())
				.filter(LibraryToExprGenerator::isPublic).filter(m -> !isObjectMethod(m))
				.collect(Collectors.groupingBy(Method::getName, LinkedHashMap::new, Collectors.toList()));

		String functions = grouped.values().stream().flatMap(List::stream).map(LibraryToExprGenerator::toFunctionDecl)
				.flatMap(Optional::stream).collect(Collectors.joining(System.lineSeparator()));
//		System.out.println("Generated " + functions);
		return "// Generated by LibraryToExprGenerator from " + libraryClass.getName() + System.lineSeparator()
				+ functions + System.lineSeparator();
	}

	/**
	 * Converts a single method to a {@code function ...} declaration, or empty if
	 * void.
	 */
	private static Optional<String> toFunctionDecl(Method method) {
		String returnExpr = toExprType(method.getGenericReturnType());
		if (returnExpr == null)
			return Optional.empty();

		String params = IntStream.range(0, method.getParameterCount())
				.mapToObj(i -> toExprType(method.getGenericParameterTypes()[i]) + " " + parameterName(method, i))
				.collect(Collectors.joining(", "));

		return Optional.of("function " + returnExpr + " " + method.getName() + "(" + params + ")");
	}

	// -- Type mapping: Java Type → expr type string ---------------------------

	/**
	 * Maps a Java {@link Type} to an expr type string; returns {@code null} for
	 * void.
	 */
	public static String toExprType(Type type) {
		return switch (type) {
		case Class<?> c when c == void.class || c == Void.class -> null;
		case Class<?> cls -> rawClassToExpr(cls);
		case ParameterizedType pt -> parameterizedToExpr(pt);
		case TypeVariable<?> tv -> "any";
		default -> "any";
		};
	}

	private static final Map<Class<?>, String> TYPE_MAP = Map.ofEntries(Map.entry(boolean.class, "bool"),
			Map.entry(Boolean.class, "bool"), Map.entry(long.class, "int"), Map.entry(Long.class, "int"),
			Map.entry(int.class, "int"), Map.entry(Integer.class, "int"), Map.entry(short.class, "int"),
			Map.entry(Short.class, "int"), Map.entry(byte.class, "int"), Map.entry(Byte.class, "int"),
			Map.entry(double.class, "real"), Map.entry(Double.class, "real"), Map.entry(float.class, "real"),
			Map.entry(Float.class, "real"), Map.entry(BigDecimal.class, "real"), Map.entry(String.class, "string"));

	private static String rawClassToExpr(Class<?> cls) {
		String mapped = TYPE_MAP.get(cls);
		if (mapped != null)            return mapped;
		// EMF expression model types
		if (ExpressionVector.class.isAssignableFrom(cls)) return "any[]";
		if (ExpressionMap.class.isAssignableFrom(cls))    return "map<any, any>";
		if (Expression.class.isAssignableFrom(cls))       return "any";
		// Java collection / map types
		if (Collection.class.isAssignableFrom(cls))       return "any[]";
		if (Map.class.isAssignableFrom(cls))              return "map<any, any>";
		return "any";
	}

	private static String parameterizedToExpr(ParameterizedType pt) {
		Class<?> raw = (Class<?>) pt.getRawType();
		Type[] args = pt.getActualTypeArguments();

		if (Collection.class.isAssignableFrom(raw)) {
			return (args.length > 0 ? toExprType(args[0]) : "any") + "[]";
		}
		if (Map.class.isAssignableFrom(raw)) {
			return "map<" + (args.length > 0 ? toExprType(args[0]) : "any") + ", "
					+ (args.length > 1 ? toExprType(args[1]) : "any") + ">";
		}
		return rawClassToExpr(raw);
	}

	// -- Helpers --------------------------------------------------------------

	private static boolean isPublic(Method m) {
		return Modifier.isPublic(m.getModifiers());
	}

	private static boolean isPublicStatic(Method m) {
		return Modifier.isPublic(m.getModifiers()) && Modifier.isStatic(m.getModifiers());
	}

	private static boolean isObjectMethod(Method m) {
		try {
			Object.class.getMethod(m.getName(), m.getParameterTypes());
			return true;
		} catch (NoSuchMethodException e) {
			return false;
		}
	}

	/**
	 * Uses the real parameter name if compiled with {@code -parameters}, else
	 * {@code pN}.
	 */
	private static String parameterName(Method method, int index) {
		Parameter p = method.getParameters()[index];
		return p.isNamePresent() ? "_" +p.getName() : "p" + index;
	}
}
