/**
 * Copyright (c) 2024, 2025 TNO-ESI
 *
 * See the NOTICE file(s) distributed with this work for additional
 * information regarding copyright ownership.
 *
 * This program and the accompanying materials are made available
 * under the terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT
 *
 * SPDX-License-Identifier: MIT
 */
/*
 * generated by Xtext 2.19.0
 */
package nl.esi.comma.steps.validation

import nl.esi.comma.systemconfig.configuration.ConfigurationPackage
import org.eclipse.emf.ecore.EClass

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class StepValidator extends AbstractStepValidator {
    override protected isValidImportType(EClass importType) {
        return ConfigurationPackage.Literals.FEATURE_DEFINITION.isSuperTypeOf(importType)
    }
}
