/**
 * Copyright (c) 2024, 2025 TNO-ESI
 *
 * See the NOTICE file(s) distributed with this work for additional
 * information regarding copyright ownership.
 *
 * This program and the accompanying materials are made available
 * under the terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT
 *
 * SPDX-License-Identifier: MIT
 */
/*
 * generated by Xtext 2.36.0
 */
package nl.asml.matala.server.tests

import java.io.ByteArrayInputStream
import java.util.List
import nl.esi.xtext.types.TypesStandaloneSetup
import nl.esi.xtext.types.types.TypesModel
import org.eclipse.emf.common.util.URI
import org.eclipse.emf.ecore.resource.ResourceSet
import org.eclipse.xtext.resource.XtextResourceSet
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith

import nl.esi.xtext.common.lang.utilities.EcoreUtil3
import static extension nl.asml.matala.server.types.outline.TypesOutlineGenerator.*
import nl.asml.matala.server.types.outline.DataTypeOutlineEntry

/**
 * Tests transformation from TypesModel to DataTypeListSchema.
 * Directly creates ResourceSet with Types language support to parse .types files.
 */
@ExtendWith(InjectionExtension)
class TypesOutlineGeneratorTest {
	
	var ResourceSet resourceSet
	
	new() {
		// Initialize Types language support
		new TypesStandaloneSetup().createInjectorAndDoEMFRegistration()
		resourceSet = new XtextResourceSet
	}
	

@Test
    def void loadRecordList() {
        val typesCode = '''
            record CorrectionItem {
              concrete string data
            }
            record CorrectionsReport {
              mixed map<int, CorrectionItem[]> correctionsMap
              concrete int id
            }
        '''
        val resource = resourceSet.createResource(URI.createURI("test.types"))
        resource.load(new ByteArrayInputStream(typesCode.bytes), null)
        
        val typesModel = resource.contents.filter(TypesModel).head
        Assertions.assertNotNull(typesModel, "TypesModel should be parsed from types syntax")
        val errors = resource.errors
        Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
    }
    
	@Test
    def void loadContext() {
        val typesCode = '''
        @id("DataType_02hh0t9")
        record Fries {
          concrete Topping dressing
          concrete string client_id
        }
        @id("DataType_17t5tar")
        @typeAlias("Context")
        record FriesContext {
          concrete string client_id
        }
        @id("DataType_1jk4lpg")
        enum Sauce {
          Ketchup
          Mayo
        }
        @id("DataType_2v8mfd7")
        record Topping {
          concrete FriesContext ctx
          concrete Sauce sauce
        }  
        '''
        val expected = '''
        [
          {
            "nodeType": "Context",
            "id": "DataType_17t5tar",
            "name": "FriesContext",
            "label": "FriesContext : Context",
            "children": [
              {
                "nodeType": "Context",
                "name": "client_id",
                "label": "client_id : String",
                "kind": "concrete",
                "children": []
              }
            ]
          }
        ]
        '''
        val resource = resourceSet.createResource(URI.createURI("test.types"))
        resource.load(new ByteArrayInputStream(typesCode.bytes), null)
        
        val typesModel = resource.contents.filter(TypesModel).head
        Assertions.assertNotNull(typesModel, "TypesModel should be parsed from types syntax")
        val errors = resource.errors
        Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
        compare("FriesContext", typesModel, expected )
   
    }
   
	@Test
	def void loadTypesModel() {
		val typesCode = '''
        @id("aap")
        enum Color { RED GREEN BLUE }        
		'''
		val expected = '''
        [
          {
            "nodeType": "Enum",
            "id": "aap",
            "name": "Color",
            "label": "Color : Enum",
            "children": [
              {
                "nodeType": "enum-literal",
                "name": "BLUE",
                "label": "BLUE",
                "children": []
              },
              {
                "nodeType": "enum-literal",
                "name": "GREEN",
                "label": "GREEN",
                "children": []
              },
              {
                "nodeType": "enum-literal",
                "name": "RED",
                "label": "RED",
                "children": []
              }
            ]
          }
        ]
		'''
		val resource = resourceSet.createResource(URI.createURI("test.types"))
		resource.load(new ByteArrayInputStream(typesCode.bytes), null)
		
		val typesModel = resource.contents.filter(TypesModel).head
		Assertions.assertNotNull(typesModel, "TypesModel should be parsed from types syntax")
		val errors = resource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
		compare("Color", typesModel, expected )
	}
	
	@Test
	def void transformEnumToDataType() {
		val typesCode = '''
			enum Color { RED GREEN BLUE }
		'''
		val resource = resourceSet.createResource(URI.createURI("test2.types"))
		resource.load(new ByteArrayInputStream(typesCode.bytes), null)
		
		val typesModel = resource.contents.filter(TypesModel).head
		Assertions.assertNotNull(typesModel, "TypesModel should parse successfully")
		
		val entries = typesModel.outline
		
		println(entries.toJson)
		Assertions.assertNotNull(entries)
		Assertions.assertFalse(entries.isEmpty, "Schema should have entries")
		
		val colorEntry = entries.head.children.head
		Assertions.assertEquals("RED", colorEntry.label)
	}

	
    @Test
    def void transformPrinter() {
        transformPrinter(null,null)
    }

    @Test
    def void transformPrinterPrintRequest() {
        val compare = '''
        [
          {
            "nodeType": "Record",
            "name": "PrintRequest",
            "label": "PrintRequest : Record",
            "children": [
              {
                "nodeType": "record-field",
                "name": "color",
                "label": "color : ColorType : Enum",
                "kind": "concrete",
                "children": [
                  {
                    "nodeType": "enum-literal",
                    "name": "COLOR",
                    "label": "COLOR",
                    "children": []
                  },
                  {
                    "nodeType": "enum-literal",
                    "name": "MONOCHROME",
                    "label": "MONOCHROME",
                    "children": []
                  }
                ]
              },
              {
                "nodeType": "record-field",
                "name": "id",
                "label": "id : Int",
                "kind": "concrete",
                "children": []
              },
              {
                "nodeType": "record-field",
                "name": "opType",
                "label": "opType : OperationType : Enum",
                "kind": "concrete",
                "children": [
                  {
                    "nodeType": "enum-literal",
                    "name": "PREP",
                    "label": "PREP",
                    "children": []
                  },
                  {
                    "nodeType": "enum-literal",
                    "name": "PRINT",
                    "label": "PRINT",
                    "children": []
                  }
                ]
              },
              {
                "nodeType": "record-field",
                "name": "resolution",
                "label": "resolution : PrintResolution : Enum",
                "kind": "concrete",
                "children": [
                  {
                    "nodeType": "enum-literal",
                    "name": "HIGH",
                    "label": "HIGH",
                    "children": []
                  },
                  {
                    "nodeType": "enum-literal",
                    "name": "LOW",
                    "label": "LOW",
                    "children": []
                  },
                  {
                    "nodeType": "enum-literal",
                    "name": "MED",
                    "label": "MED",
                    "children": []
                  }
                ]
              },
              {
                "nodeType": "record-field",
                "name": "scale",
                "label": "scale : Float",
                "kind": "concrete",
                "children": []
              }
            ]
          }
        ]
        '''
        transformPrinter("PrintRequest", compare)
    }
    
        @Test
    def void transformList() {
        val value = "«value»"
        val element = "«element»"
        val compare = '''
        [
          {
            "nodeType": "Record",
            "name": "CorrectionsReport",
            "label": "CorrectionsReport : Record",
            "children": [
              {
                "nodeType": "record-field",
                "name": "correctionsMap",
                "label": "correctionsMap : Map<Int, List<CorrectionItem : Record>>",
                "kind": "mixed",
                "children": [
                  {
                    "nodeType": "map-value",
                    "name": "value",
                    "label": "«value» : List<CorrectionItem : Record>",
                    "children": [
                      {
                        "nodeType": "collection-element",
                        "name": "element",
                        "label": "«element» : CorrectionItem : Record",
                        "children": [
                          {
                            "nodeType": "record-field",
                            "name": "data",
                            "label": "data : String",
                            "kind": "concrete",
                            "children": []
                          }
                        ]
                      }
                    ]
                  }
                ]
              },
              {
                "nodeType": "record-field",
                "name": "id",
                "label": "id : Int",
                "kind": "concrete",
                "children": []
              }
            ]
          }
        ]
		'''
        transformPrinter("CorrectionsReport", compare)
    }
    

    def void transformPrinter(String typeName, String expectJsonString) {
        var fileName = "printer.types"
        val resource = resourceSet.createResource(URI.createURI(fileName))
        resource.load(this.class.getResourceAsStream(fileName), null)
        EcoreUtil3.resolveAll(resourceSet)
        val typesModel = resource.contents.filter(TypesModel).head
        compare(typeName, typesModel, expectJsonString)
    }
    
    def void compare(String typeName, TypesModel typesModel, String expectJsonString){
        EcoreUtil3.validate(typesModel)
        Assertions.assertNotNull(typesModel, "TypesModel should parse successfully")
        val actual = typesModel.getOutline(typeName)
        println(actual.toJson)
        if (expectJsonString !== null) {
            val expected = expectJsonString.fromJson
            compare(expected, actual)
        }
    }
    private static def void sortRecursively(List<DataTypeOutlineEntry> list) {
        if (!list.isEmpty) {
            list.sort[a, b | a.label.compareTo(b.label)]
            list.forEach[children.sortRecursively]
        }
    }
    
    private static def List<String> equal(DataTypeOutlineEntry a, DataTypeOutlineEntry b) {
        val mismatch = newArrayList
        if (a.nodeType != b.nodeType) mismatch += "NodeType"
        if (a.label != b.label) mismatch += "Label"
        if (a.name != b.name) mismatch += "Name"
        if (a.id != b.id) mismatch += "Id"
        if (a.children.size != b.children.size) mismatch += "Size"
        
        if (!mismatch.empty) {
            return mismatch
        }
        for (var i = 0; i < a.children.size; i++) {
            val cMismatch = a.children.get(i).equal(b.children.get(i))
            if (!cMismatch.empty){
                return cMismatch
            }
        }
        return mismatch
    }
    
    private static def void compare(List<DataTypeOutlineEntry> expected, List<DataTypeOutlineEntry> actual){
        expected.sortRecursively
        actual.sortRecursively
        // Compare structure (ignoring id differences)
        Assertions.assertEquals(actual.size, expected.size, 
            "Entry count mismatch. Expected: " + expected.size + ", Got: " + actual.size)
        for (exp: expected) {
            val act = actual.findFirst[name == exp.name]
            Assertions.assertNotNull(act)
            val matches = act.equal(exp)
            if (!matches.empty) {
                println("Mismatch in " + matches.join(",") + ", label " + act.label + ":")
                println("Expected: " + newArrayList(exp).toJson)
                println("Actual: " + newArrayList(act).toJson)
            }
            Assertions.assertTrue(matches.empty, 
                "Entry " + act.label + " (nodeType: " + act.nodeType + ") structure mismatch (labels/hierarchy differ)\n" +
                "Expected: " + List.of(exp).toJson + "\n" +
                "Actual: " + List.of(act).toJson)
        }
        println("✓ All " + actual.size + " entries match expected structure (ignoring id differences)")
    }
}

