/*
 * generated by Xtext 2.36.0
 */
package nl.esi.comma.json.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class JsonUiModule extends AbstractJsonUiModule {

	public JsonUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
