/*
 * generated by Xtext 2.36.0
 */
package nl.esi.comma.abstrracttestspecification


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class AbstractTestspecificationStandaloneSetup extends AbstractTestspecificationStandaloneSetupGenerated {

	def static void doSetup() {
		new AbstractTestspecificationStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
