/*
 * generated by Xtext 2.36.0
 */
package nl.esi.comma.testspecification

import nl.esi.comma.types.scoping.TypesImportUriGlobalScopeProvider

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class TestspecificationRuntimeModule extends AbstractTestspecificationRuntimeModule {
    override bindIGlobalScopeProvider() {
        TypesImportUriGlobalScopeProvider
    }
}
