////
  // Copyright (c) 2024, 2026 TNO-ESI
  //
  // This program and the accompanying materials are made
  // available under the terms of the Eclipse Public License 2.0
  // which is available at https://www.eclipse.org/legal/epl-2.0/
  //
  // SPDX-License-Identifier: EPL-2.0
////

include::_initCommon.adoc[]

[[xtext-languages]]
== Xtext Languages

=== Overview

Figure <<xtext-grammars>> shows a deployment diagram of all Xtext based DSLs and their relations, where:

Package::
Denotes the bundle containing the Xtext grammar.
The dashed arrows between the packages denote the bundle dependencies as defined by the `Require-Bundle` in the `MANIFEST.MF` of the bundle.

Artifact::
Denotes the grammar, which is explained in more detail in section <<language-meta-models>>.
The stereotype denotes the file extensions of the DSL.
The arrows between the artifacts denote either language reuse (i.e. `with` keyword, denoted by an open arrow) or language references (i.e. `import` keyword, denoted by a closed arrow).
For more information about the reuse of existing grammars, please read the (i.e. https://eclipse.dev/Xtext/documentation/301_grammarlanguage.html#grammar-mixins[Grammar Mixins]) section of the Xtext documentation.

[[xtext-grammars]]
.Xtext languages and their relations
[plantuml, images/xtext-grammars, png]
....
@startuml

include::{gendocdir}/xtext-grammars.plantuml[]

artifact nl.esi.xtext.types.Types #white/aqua

@enduml
....

<<<

include::{extdocdir}/nl.esi.xtext.types.adoc[leveloffset=2]

include::{extdocdir}/nl.esi.xtext.expressions.adoc[leveloffset=2]
include::{extdocdir}/expression-functions-framework-design.adoc[leveloffset=2]
